Stat svc
Michail-A/java-explore-with-me pull request #1
Opened 2024-01-14 14:54 UTC by Michail-A

2024-01-17 18:44 UTC, NikolaiDem requested changes

2024-01-17 18:44 UTC, NikolaiDem commented on main/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
${project.version}

2024-01-17 18:44 UTC, NikolaiDem commented on stat/client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
${project.vesion}

2024-01-17 18:44 UTC, NikolaiDem commented on stat/server/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
${project.version}

2024-01-17 18:44 UTC, NikolaiDem commented on stat/server/src/main/java/ru/practicum/ewm/stat/server/HitModel.java
> +package ru.practicum.ewm.stat.server;
Расположить классы по пакетам

2024-01-17 18:44 UTC, NikolaiDem commented on stat/server/src/main/resources/schema.sql
> +
Еще лучше сделать таблицу с приложениями, где будет его id и название. Таким образом при изменении, например, названия приложения не придется обновлять всю таблицу hits.

2024-01-24 00:56 UTC, Michail-A commented on stat/server/src/main/resources/schema.sql
> +
Если я правильно понял
У нас сейчас одно приложение и других не планируется, и поскольку в тестах мы принимаем json со string названием приложения, придется отдельно прописывать логику выбора нужного названия приложения.

Если где то не прав, прошу уточнить, реализую во второй части

2024-01-24 00:58 UTC, Michail-A commented on stat/server/src/main/resources/schema.sql
> +
id; id.app; uri; ip; timestamp  - такие поля в основной таблице предлагаете?

2024-01-24 21:40 UTC, NikolaiDem approved these changes

2024-01-24 21:40 UTC, NikolaiDem commented on stat/server/src/main/resources/schema.sql
> +
> Если я правильно понял У нас сейчас одно приложение и других не планируется, и поскольку в тестах мы принимаем json со string названием приложения, придется отдельно прописывать логику выбора нужного названия приложения.
> 
> Если где то не прав, прошу уточнить, реализую во второй части
Да, появится доп логика выбора приложения по его названию.

> id; id.app; uri; ip; timestamp - такие поля в основной таблице предлагаете?
 Да

2024-02-04 01:50 UTC, merged